version: 2
updates:
  - package-ecosystem: "terraform"
    assignees: ["frasermolyneux"]
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:45"
      timezone: "Etc/UTC"
    groups:
      terraform:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    assignees: ["frasermolyneux"]
    directory: "/terraform-sub"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:45"
      timezone: "Etc/UTC"
    groups:
      terraform:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    assignees: ["frasermolyneux"]
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:45"
      timezone: "Etc/UTC"
    groups:
      github-actions:
        patterns:
          - "*"