name: Code Quality

on: [push, pull_request]

jobs:
  quality:
    uses: frasermolyneux/actions/.github/workflows/codequality.yml@main
    with:
      sonar-project-key: frasermolyneux_platform-monitoring
      sonar-organization: frasermolyneux
      sonar-host-url: https://sonarcloud.io
      build-target: dotnet-func-ci
      dotnet-project: monitoring-func
      dotnet-version: 9.0.x
      src-folder: src
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
